
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME} 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - server
  
    nginx:
      image: nginx:alpine
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./ssl:/etc/nginx/ssl:ro
        - ./nginx.conf:/etc/nginx/nginx.conf
  #      - ./client/build:/usr/share/nginx/html # Статические файлы клиента
      depends_on:
        - server
        - client
volumes:
  postgres_data:
