"""add uniq subs table

Revision ID: dad18fe8be4a
Revises: 0a5866e09fc9
Create Date: 2024-11-29 22:30:02.771542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dad18fe8be4a'
down_revision: Union[str, None] = '0a5866e09fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_user_query', 'subscriptions', ['user_id', 'query_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_query', 'subscriptions', type_='unique')
    # ### end Alembic commands ###
